/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-09-24 03:33:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class formDoiLichThi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sắp xếp lịch thi</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/CDLT.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/base.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/grid.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"app\">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"grid wide\">\r\n");
      out.write("                <img class=\"header_img\" src=\"./assets/image/Poly.png\" alt=\"\">\r\n");
      out.write("                <img class=\"header_icon_user\" src=\"./assets/image/user.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col container_middle\">\r\n");
      out.write("                    <p class=\"h1 container_header\">\r\n");
      out.write("                        CÔNG CỤ CHUYỂN ĐỔI LỊCH THI\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <form action=\"\">\r\n");
      out.write("                        <div class=\"container_body\">\r\n");
      out.write("                            <div class=\"container_body-button\">\r\n");
      out.write("                                <button class=\"btnFile\">\r\n");
      out.write("                                    CHỌN FILE EXCEL\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"container_body-cbb\">\r\n");
      out.write("                                <div class=\"btn-group\">\r\n");
      out.write("                                    <select id=\"selectFile\" class=\"form-select form-select-lg mb-3 cbb\"\r\n");
      out.write("                                        aria-label=\".form-select-lg example\" onchange=\"getValueSelected();\">\r\n");
      out.write("                                        <option value=\"keHoachThi\">KẾ HOẠCH THI</option>\r\n");
      out.write("                                        <option value=\"bangDiem\">BẢNG ĐIỂM</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"rdo-group \" id=\"modalCBB\">\r\n");
      out.write("                                    <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\"\r\n");
      out.write("                                            id=\"inlineRadio1\" value=\"option1\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"inlineRadio1\">ĐIỂM QUIZ</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\"\r\n");
      out.write("                                            id=\"inlineRadio2\" value=\"option2\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"inlineRadio2\">ĐIỂM ONLINE</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-check form-check-inline\">\r\n");
      out.write("                                        <input class=\"form-check-input\" type=\"radio\" name=\"inlineRadioOptions\"\r\n");
      out.write("                                            id=\"inlineRadio3\" value=\"option3\">\r\n");
      out.write("                                        <label class=\"form-check-label\" for=\"inlineRadio3\">ĐIỂM DANH</label>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"container_body-submit\">\r\n");
      out.write("                                <button class=\"btn_submit\">SUBMIT</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"container_footer\">\r\n");
      out.write("                    <div class=\"container_footer-download\">\r\n");
      out.write("                        <a href=\"\"><img src=\"./assets/image/241315670_374048297772326_2602951087702346768_n.png\"\r\n");
      out.write("                                alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        var text;\r\n");
      out.write("        var select;\r\n");
      out.write("        var modal = document.getElementById(\"modalCBB\");\r\n");
      out.write("        console.log(modal);\r\n");
      out.write("\r\n");
      out.write("        function getValueSelected() {\r\n");
      out.write("            select = document.getElementById(\"selectFile\");\r\n");
      out.write("            text = select.options[select.selectedIndex].text;\r\n");
      out.write("\r\n");
      out.write("            if (text === \"BẢNG ĐIỂM\") {\r\n");
      out.write("                showCBB();\r\n");
      out.write("            } else {\r\n");
      out.write("                hideCBB();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showCBB() {\r\n");
      out.write("            modal.classList.add('open');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function hideCBB() {\r\n");
      out.write("            modal.classList.remove('open');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
