/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-09-24 03:28:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class HomeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Home</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/home.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/base.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/grid.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("        integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/fontawesome-free-5.15.3-web/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"Container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-2 container_left\">\r\n");
      out.write("                <div class=\"container_left-header\">\r\n");
      out.write("                    <img src=\"./assets/image/Poly.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"container_left-body\">\r\n");
      out.write("                    <button class=\"container_left-body-btn\">DashBoard</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-10 container_right\">\r\n");
      out.write("                <div class=\"container_right-header\">\r\n");
      out.write("                    <div class=\"container_right-header-TT\">\r\n");
      out.write("                        <img class=\"header_right-icon_user\" src=\"./assets/image/user.png\" alt=\"\">\r\n");
      out.write("                        <h4 class=\"header_right-name_user\">Nguyễn Lê Hải</h4>\r\n");
      out.write("                        <button class=\"header_right-btn_user\">Đăng xuất</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"container container_right-body\">\r\n");
      out.write("                    <div class=\"container_right-body-intro\">\r\n");
      out.write("                        <h2>Danh sách ca thi</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"container container_right-body-controller\">\r\n");
      out.write("                        <div class=\"container_right-body-controller-header\">\r\n");
      out.write("                            <div class=\"container_right-body-controller-header-left\">\r\n");
      out.write("                                <a href=\"\"><i class=\"fas fa-plus plus\"></i>Thêm mới</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"container_right-body-controller-header-right\">\r\n");
      out.write("                                <select class=\"form-select form-select-lg mb-3 cbb\"\r\n");
      out.write("                                    aria-label=\".form-select-lg example\">\r\n");
      out.write("                                    <option value=\"20\">20</option>\r\n");
      out.write("                                    <option value=\"40\">40</option>\r\n");
      out.write("                                    <option value=\"60\">60</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"container_right-body-controller-table\">\r\n");
      out.write("                            <table class=\"table table-striped\">\r\n");
      out.write("                                <thead class=\"thead-dark\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"col\">TT</th>\r\n");
      out.write("                                        <th scope=\"col\">Học kỳ</th>\r\n");
      out.write("                                        <th scope=\"col\">Block</th>\r\n");
      out.write("                                        <th scope=\"col\">Trạng thái</th>\r\n");
      out.write("                                        <th scope=\"col\">Thao tác</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\">1</th>\r\n");
      out.write("                                        <td><a href=\"\">Fall 2021</a></td>\r\n");
      out.write("                                        <td>1</td>\r\n");
      out.write("                                        <td>Đang hoạt động</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <button class=\"button_update\">Cập nhật</button>\r\n");
      out.write("                                            <button class=\"button_edit\">Chỉnh sửa</button>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\">2</th>\r\n");
      out.write("                                        <td><a href=\"\">Summer 2021</a></td>\r\n");
      out.write("                                        <td>2</td>\r\n");
      out.write("                                        <td>Đã kết thúc</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <button class=\"button_update\">Cập nhật</button>\r\n");
      out.write("                                            <button class=\"button_edit\">Chỉnh sửa</button>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\">3</th>\r\n");
      out.write("                                        <td><a href=\"\">Summer 2021</a></td>\r\n");
      out.write("                                        <td>1</td>\r\n");
      out.write("                                        <td>Đã kết thúc</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <button class=\"button_update\">Cập nhật</button>\r\n");
      out.write("                                            <button class=\"button_edit\">Chỉnh sửa</button>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"container container_right-body-footer\">\r\n");
      out.write("                            <nav aria-label=\"Page navigation example\">\r\n");
      out.write("                                <ul class=\"pagination pagination-lg\">\r\n");
      out.write("                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Previous</a></li>\r\n");
      out.write("                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">Next</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
